name: analyze-wishlist

on:
  schedule:
    - cron: '0 4 */7 * *' # 4:00 UTC every 7 days
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: setup Python with uv
        id: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
            version: latest
            python-version: ${{ matrix.python-version }}
            enable-cache: true
            prune-cache: false # do not remove pre-built wheels
            ignore-nothing-to-cache: true
            cache-dependency-glob: "**/requirements.txt"

      - name: hint on cache hit
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Hit cache"

      - name: install dependencies
        run: uv pip install -r requirements.txt

      - name: execute py script
        run: python swc.py -i=${{ secrets.STEAM_ID }} -d=True

      - name: check changes
        id: check_changes
        run: if [[ $(git diff --name-only HEAD) == *"output/successful.txt"* ]]; then echo "changes=true" > "$GITHUB_OUTPUT"; else echo "changes=false" > "$GITHUB_OUTPUT"; fi

      - name: commit files
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update wishlist data." -a

      - name: push changes
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Stash png outputs
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          git add -f output/*.png
          git stash

      - name: checkout output branch
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Get png outputs from stash
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          set -e
          git stash apply || true
          git checkout --theirs -- output/*.png
          git stash drop

      - name: commit plots
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --amend --no-edit

      - name: push plots to output branch
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: True
